Updates
ergoplatform/awesome-ergo pull request #4
Opened 2021-07-03 12:59 UTC by glasgowm148

Updated pages and organised them up a bit. Also added a spot for logos, etc.

2021-07-04 17:04 UTC, aslesarenko requested changes
Please remove .DS_Store files, otherwise looks good, thanks.

2021-07-05 08:47 UTC, aslesarenko reviewed
Just noticed another issue. This list of devs is far from being complete. Maybe instead of devs, we should list all the known projects (including the recent ones like ergo-wallet-android)

2021-07-06 08:16 UTC, glasgowm148 commented
> Just noticed another issue. This list of devs is far from being complete (https://github.com/glasgowm148/awesome-ergo/blob/master/pages/devs.md#devs). Maybe instead of devs, we should list all the known projects (including the recent ones like ergo-wallet-android)

Good idea, I was just listing the ones I knew off-hand as people often complained Ergo's GitHub's weren't very active (without realising actual development was spread all over GitHub). Will have a look and repush.

2021-07-10 13:02 UTC, aslesarenko approved these changes

2021-07-13 10:08 UTC, merged